# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtMultimedia
from random import randint, choice


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # This variable serves for the games against the computer.
        self.vs = False
        # This variable maks the end of the game.
        self.game_finish = False
        # This variable serves the computer to know which symbol the user has X or O.
        # This variable is only important for games against the computer and it is invariant during the game.
        self.gamer = 2
        # This variable serves the computer to know which symbol the user has X or O
        # and it can change during the game.
        self.number = 2
        # This variable serves to save the status CSS of the buttons, which may have an X or O.
        self.estado = ["QPushButton{\n"
                       "background-color: rgb(255, 255, 255);\n"
                       "border-radius: 10px;\n"
                       "background-image: url(:/image/x1.png);\n"
                       "background-position: center;\n"
                       "background-repeat: None\n"
                       "}\n"
                       "QPushButton:hover{\n"
                       "border: 4px solid rgb(255, 249, 75)\n"
                       "}\n"
                       "QPushButton:pressed {    \n"
                       "    background-color: rgb(255, 249, 75);\n"
                       "    border: 2px solid rgb(255, 249, 75);    \n"
                       "}",
                       "QPushButton{\n"
                       "background-image: url(:/image/o2.png);\n"
                       "background-repeat: None;\n"
                       "background-position: center;\n"
                       "background-color: rgb(69, 84, 79);\n"
                       "border-radius: 10px\n"
                       "}\n"
                       "QPushButton:hover{\n"
                       "border: 4px solid rgb(255, 249, 75)\n"
                       "}\n"
                       "QPushButton:pressed {    \n"
                       "    background-color: rgb(255, 249, 75);\n"
                       "    border: 2px solid rgb(255, 249, 75);    \n"
                       "}",
                       """QPushButton{\n
        background-color: rgb(250, 250, 0);\n
        border-radius: 10px\n
        }\n
        QPushButton:hover{\n
        border: 4px solid rgb(255, 249, 75)\n
        }\n
        QPushButton:pressed {    \n
            background-color: rgb(255, 249, 75);\n
            border: 2px solid rgb(255, 249, 75);    \n
        }""",
                       "QPushButton{\n"
                       "color: rgb(255, 255, 255);\n"
                       "font: italic 23pt \"Times New Roman\";\n"
                       "background-color: rgb(54, 121, 106);\n"
                       "border-radius: 7px;\n"
                       "background-position: center;\n"
                       "background-repeat: None\n"
                       "}\n"
                       "QPushButton:hover{\n"
                       "border: 2px solid rgb(0, 254, 203)\n"
                       "}\n"
                       "QPushButton:pressed {    \n"
                       "    background-color: rgb(0, 254, 203);\n"
                       "    border: 2px solid rgb(0, 254, 203);    \n"
                       "}",
                       "QPushButton{\n"
                       "color: rgb(255, 255, 255);\n"
                       "font: italic 23pt \"Times New Roman\";\n"
                       "background-color: rgb(0, 254, 203);\n"
                       "border-radius: 7px;\n"
                       "}\n"]
        # This variable serves so that the computer doesn't play twice at the same time when the user
        # plays against the computer. It will receive o Boolean value if it is True the computer can play.
        self.goo = None
        # This variable is for the computer to know where the X and O are positioned.
        # Nothing = 2
        # X = 0
        # O = 1
        self.place = [2, 2, 2, 2, 2, 2, 2, 2, 2]
        # This variable will be used to play music during the game.
        self.sound = None
        # creating the main window.
        MainWindow.setObjectName("MainWindow")
        # adding a icon.
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/icon3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.resize(1000, 701)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 701))
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainWindow)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_main = QtWidgets.QFrame(MainWindow)
        self.frame_main.setStyleSheet("background-color: rgb(0, 254, 203);\n"
                                      "background-color: qlineargradient(spread:pad, x1:0.565, y1:0.789773, x2:0.458, y2:0, stop:0 rgba(222, 62, 255, 255), stop:1 rgba(0, 254, 203, 255));")
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.frame_main)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_top.setStyleSheet("background-color: rgb(69, 84, 79);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.restart_button = QtWidgets.QPushButton(self.frame_top)
        self.restart_button.setMinimumSize(QtCore.QSize(40, 40))
        self.restart_button.setMaximumSize(QtCore.QSize(40, 16777215))
        self.restart_button.setStyleSheet("QPushButton{\n"
                                          "background-color: rgb(54, 121, 106);\n"
                                          "border-radius: 7px;\n"
                                          "    background-image: url(:/image/restart2.png);\n"
                                          "background-position: center;\n"
                                          "background-repeat: None\n"
                                          "}\n"
                                          "QPushButton:hover{\n"
                                          "border: 2px solid rgb(255, 249, 75)\n"
                                          "}\n"
                                          "QPushButton:pressed {    \n"
                                          "    background-color: rgb(255, 249, 75);\n"
                                          "    border: 2px solid rgb(255, 249, 75);    \n"
                                          "}")
        self.restart_button.setText("")
        self.restart_button.setObjectName("restart_button")
        self.restart_button.setToolTip("Novo jogo")
        self.horizontalLayout_3.addWidget(self.restart_button)
        self.vs_button = QtWidgets.QPushButton(self.frame_top)
        self.vs_button.setMinimumSize(QtCore.QSize(40, 40))
        self.vs_button.setMaximumSize(QtCore.QSize(40, 16777215))
        self.vs_button.setStyleSheet(self.estado[3])
        self.vs_button.setObjectName("vs_button")
        self.horizontalLayout_3.addWidget(self.vs_button)
        spacerItem = QtWidgets.QSpacerItem(276, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_top)
        self.label.setStyleSheet("font: 75 16pt \"Times New Rom\";\n"
                                 "font: 22pt \"Times New Roman\";\n"
                                 "color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(276, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.About_button = QtWidgets.QPushButton(self.frame_top)
        self.About_button.setMinimumSize(QtCore.QSize(40, 40))
        self.About_button.setMaximumSize(QtCore.QSize(40, 16777215))
        self.About_button.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(54, 121, 106);\n"
                                        "border-radius: 7px;\n"
                                        "background-image: url(:/image/About.png);\n"
                                        "background-position: center;\n"
                                        "background-repeat: None\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "border: 2px solid rgb(250, 0, 168)\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: rgb(250, 0, 168);\n"
                                        "    border: 2px solid rgb(250, 0, 168);    \n"
                                        "}")
        self.About_button.setText("")
        self.About_button.setObjectName("About_button")
        self.horizontalLayout_3.addWidget(self.About_button)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_centrale = QtWidgets.QFrame(self.frame_main)
        self.frame_centrale.setStyleSheet("")
        self.frame_centrale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_centrale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_centrale.setObjectName("frame_centrale")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_centrale)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(80, 30, 80, 30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_board = QtWidgets.QFrame(self.frame_centrale)
        self.frame_board.setStyleSheet("background-color: rgb(69, 84, 79, 200);\n"
                                       "border-radius: 50px")
        self.frame_board.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_board.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_board.setObjectName("frame_board")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_board)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(36, 35, 36, 36)
        self.gridLayout.setHorizontalSpacing(18)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_board)
        self.pushButton_4.setMinimumSize(QtCore.QSize(200, 160))
        self.pushButton_4.setStyleSheet(self.estado[2])
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 3, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_board)
        self.pushButton_9.setMinimumSize(QtCore.QSize(200, 160))
        self.pushButton_9.setStyleSheet(self.estado[2])
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 5, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_board)
        self.pushButton_6.setMinimumSize(QtCore.QSize(200, 160))
        self.pushButton_6.setStyleSheet(self.estado[2])
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 3, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_board)
        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 160))
        self.pushButton_3.setStyleSheet(self.estado[2])
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_board)
        self.pushButton_7.setMinimumSize(QtCore.QSize(200, 160))
        self.pushButton_7.setStyleSheet(self.estado[2])
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 5, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_board)
        self.pushButton_5.setMinimumSize(QtCore.QSize(200, 160))
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 200))
        self.pushButton_5.setStyleSheet(self.estado[2])
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_board)
        self.pushButton_8.setMinimumSize(QtCore.QSize(200, 160))
        self.pushButton_8.setStyleSheet(self.estado[2])
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 5, 1, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.frame_board)
        self.pushButton_1.setMinimumSize(QtCore.QSize(200, 160))
        self.pushButton_1.setStyleSheet(self.estado[2])
        self.pushButton_1.setText("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_board)
        self.pushButton_2.setMinimumSize(QtCore.QSize(200, 160))
        self.pushButton_2.setStyleSheet(self.estado[2])
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 3, 1)
        self.horizontalLayout_2.addWidget(self.frame_board)
        self.verticalLayout.addWidget(self.frame_centrale)
        self.horizontalLayout.addWidget(self.frame_main)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Giving functionalities to every click that the user makes.
        self.pushButton_1.clicked.connect(lambda: self.click(key="1"))
        self.pushButton_2.clicked.connect(lambda: self.click(key="2"))
        self.pushButton_3.clicked.connect(lambda: self.click(key="3"))
        self.pushButton_4.clicked.connect(lambda: self.click(key="4"))
        self.pushButton_5.clicked.connect(lambda: self.click(key="5"))
        self.pushButton_6.clicked.connect(lambda: self.click(key="6"))
        self.pushButton_7.clicked.connect(lambda: self.click(key="7"))
        self.pushButton_8.clicked.connect(lambda: self.click(key="8"))
        self.pushButton_9.clicked.connect(lambda: self.click(key="9"))
        self.restart_button.clicked.connect(lambda: self.click(key="new_game", event="restart"))
        self.vs_button.clicked.connect(lambda: self.click(key="VS", event="restart"))
        # Importing the window about.
        from about import Ui_MainWindow2
        # creating the window about which will be daughter of the main window.
        self.AboutWindow = QtWidgets.QMainWindow(parent=MainWindow)
        self.ui = Ui_MainWindow2()
        self.ui.setupUi(self.AboutWindow)
        # Showing the window about created.
        self.About_button.clicked.connect(lambda: self.AboutWindow.show())

    # Function for button clicks.
    def click(self, key: str = "", event: str = ""):
        # Putting sound to play when the user is clicking on the buttons.
        if key in ["1", "2", "3", "4", "5", "6", "7", "8", "9"]:
            self.sound = QtMultimedia.QSound("click.wav")
            self.sound.play()
        if event == "restart":
            self.pushButton_1.setDisabled(False)
            self.pushButton_1.setStyleSheet(self.estado[2])
            self.pushButton_2.setDisabled(False)
            self.pushButton_2.setStyleSheet(self.estado[2])
            self.pushButton_3.setDisabled(False)
            self.pushButton_3.setStyleSheet(self.estado[2])
            self.pushButton_4.setDisabled(False)
            self.pushButton_4.setStyleSheet(self.estado[2])
            self.pushButton_5.setDisabled(False)
            self.pushButton_5.setStyleSheet(self.estado[2])
            self.pushButton_6.setDisabled(False)
            self.pushButton_6.setStyleSheet(self.estado[2])
            self.pushButton_7.setDisabled(False)
            self.pushButton_7.setStyleSheet(self.estado[2])
            self.pushButton_8.setDisabled(False)
            self.pushButton_8.setStyleSheet(self.estado[2])
            self.pushButton_9.setDisabled(False)
            self.pushButton_9.setStyleSheet(self.estado[2])

            # These are the variables that control the game.
            self.place = [2, 2, 2, 2, 2, 2, 2, 2, 2]
            self.gamer = 2
            self.number = 2
            self.label.setText("")
            self.game_finish = False

            if key == "VS":
                if self.vs == False:
                    self.vs_button.setStyleSheet(self.estado[4])
                    self.vs = True
                else:
                    self.vs_button.setStyleSheet(self.estado[3])
                    self.vs = False


        elif key == "1":
            if self.number == 2:
                self.number = randint(0, 1)
                self.pushButton_1.setStyleSheet(self.estado[self.number])
                self.gamer = self.number

            else:
                if self.number == 0:
                    self.pushButton_1.setStyleSheet(self.estado[1])
                    self.number = 1

                else:
                    self.pushButton_1.setStyleSheet(self.estado[0])
                    self.number = 0

            self.pushButton_1.setDisabled(True)
            self.place[0] = self.number

        elif key == "2":
            if self.number == 2:
                self.number = randint(0, 1)
                self.pushButton_2.setStyleSheet(self.estado[self.number])
                self.gamer = self.number

            else:
                if self.number == 0:
                    self.pushButton_2.setStyleSheet(self.estado[1])
                    self.number = 1

                else:
                    self.pushButton_2.setStyleSheet(self.estado[0])
                    self.number = 0

            self.pushButton_2.setDisabled(True)
            self.place[1] = self.number

        elif key == "3":
            if self.number == 2:
                self.number = randint(0, 1)
                self.pushButton_3.setStyleSheet(self.estado[self.number])
                self.gamer = self.number

            else:
                if self.number == 0:
                    self.pushButton_3.setStyleSheet(self.estado[1])
                    self.number = 1

                else:
                    self.pushButton_3.setStyleSheet(self.estado[0])
                    self.number = 0

            self.pushButton_3.setDisabled(True)
            self.place[2] = self.number

        elif key == "4":
            if self.number == 2:
                self.number = randint(0, 1)
                self.pushButton_4.setStyleSheet(self.estado[self.number])
                self.gamer = self.number

            else:
                if self.number == 0:
                    self.pushButton_4.setStyleSheet(self.estado[1])
                    self.number = 1

                else:
                    self.pushButton_4.setStyleSheet(self.estado[0])
                    self.number = 0

            self.pushButton_4.setDisabled(True)
            self.place[3] = self.number

        elif key == "5":
            if self.number == 2:
                self.number = randint(0, 1)
                self.pushButton_5.setStyleSheet(self.estado[self.number])
                self.gamer = self.number

            else:
                if self.number == 0:
                    self.pushButton_5.setStyleSheet(self.estado[1])
                    self.number = 1

                else:
                    self.pushButton_5.setStyleSheet(self.estado[0])
                    self.number = 0

            self.pushButton_5.setDisabled(True)
            self.place[4] = self.number

        elif key == "6":
            if self.number == 2:
                self.number = randint(0, 1)
                self.pushButton_6.setStyleSheet(self.estado[self.number])
                self.gamer = self.number

            else:
                if self.number == 0:
                    self.pushButton_6.setStyleSheet(self.estado[1])
                    self.number = 1

                else:
                    self.pushButton_6.setStyleSheet(self.estado[0])
                    self.number = 0

            self.pushButton_6.setDisabled(True)
            self.place[5] = self.number

        elif key == "7":
            if self.number == 2:
                self.number = randint(0, 1)
                self.pushButton_7.setStyleSheet(self.estado[self.number])
                self.gamer = self.number

            else:
                if self.number == 0:
                    self.pushButton_7.setStyleSheet(self.estado[1])
                    self.number = 1

                else:
                    self.pushButton_7.setStyleSheet(self.estado[0])
                    self.number = 0

            self.pushButton_7.setDisabled(True)
            self.place[6] = self.number

        elif key == "8":
            if self.number == 2:
                self.number = randint(0, 1)
                self.pushButton_8.setStyleSheet(self.estado[self.number])
                self.gamer = self.number

            else:
                if self.number == 0:
                    self.pushButton_8.setStyleSheet(self.estado[1])
                    self.number = 1

                else:
                    self.pushButton_8.setStyleSheet(self.estado[0])
                    self.number = 0

            self.pushButton_8.setDisabled(True)
            self.place[7] = self.number

        elif key == "9":
            if self.number == 2:
                self.number = randint(0, 1)
                self.pushButton_9.setStyleSheet(self.estado[self.number])
                self.gamer = self.number

            else:
                if self.number == 0:
                    self.pushButton_9.setStyleSheet(self.estado[1])
                    self.number = 1
                else:
                    self.pushButton_9.setStyleSheet(self.estado[0])
                    self.number = 0

            self.pushButton_9.setDisabled(True)
            self.place[8] = self.number

        self.verification()

        if self.vs == True:
            self.goo = True
            lista = []
            for pos, c in enumerate(self.place):
                if c == 2:
                    lista.append(pos)
            if self.game_finish == False:
                if self.gamer == 0 and len(lista) > 1:
                    if self.goo == True and len(lista) > 1:
                        if self.place[0] == 2 and self.goo == True:
                            if 2 != self.place[4] == self.place[8] == 1 and self.place[0] == 2:
                                self.case1(num=1)
                            elif 2 != self.place[1] == self.place[2] == 1 and self.place[0] == 2:
                                self.case1(num=1)
                            elif 2 != self.place[3] == self.place[6] == 1 and self.place[0] == 2:
                                self.case1(num=1)

                        if self.place[1] == 2 and self.goo == True:
                            if 2 != self.place[0] == self.place[2] == 1 and self.place[1] == 2:
                                self.case2(num=1)
                            elif 2 != self.place[4] == self.place[7] == 1 and self.place[1] == 2:
                                self.case2(num=1)

                        if self.place[2] == 2 and self.goo == True:
                            if 2 != self.place[0] == self.place[1] == 1 and self.place[2] == 2:
                                self.case3(num=1)
                            elif 2 != self.place[4] == self.place[6] == 1 and self.place[2] == 2:
                                self.case3(num=1)
                            elif 2 != self.place[5] == self.place[8] == 1 and self.place[2] == 2:
                                self.case3(num=1)

                        if self.place[3] == 2 and self.goo == True:
                            if 2 != self.place[4] == self.place[5] == 1 and self.place[3] == 2:
                                self.case4(num=1)
                            elif 2 != self.place[0] == self.place[6] == 1 and self.place[5] == 2:
                                self.case4(num=1)

                        if self.place[4] == 2 and self.goo == True:
                            if 2 != self.place[3] == self.place[5] == 1 and self.place[4] == 2:
                                self.case5(num=1)
                            elif 2 != self.place[0] == self.place[8] == 1 and self.place[4] == 2:
                                self.case5(num=1)
                            elif 2 != self.place[1] == self.place[7] == 1 and self.place[4] == 2:
                                self.case5(num=1)
                            elif 2 != self.place[2] == self.place[6] == 1 and self.place[4] == 2:
                                self.case5(num=1)

                        if self.place[5] == 2 and self.goo == True:
                            if 2 != self.place[3] == self.place[4] == 1 and self.place[5] == 2:
                                self.case6(num=1)
                            elif 2 != self.place[2] == self.place[8] == 1 and self.place[5] == 2:
                                self.case6(num=1)

                        if self.place[6] == 2 and self.goo == True:
                            if 2 != self.place[4] == self.place[2] == 1 and self.place[6] == 2:
                                self.case7(num=1)
                            elif 2 != self.place[0] == self.place[3] == 1 and self.place[6] == 2:
                                self.case7(num=1)
                            elif 2 != self.place[7] == self.place[8] == 1 and self.place[6] == 2:
                                self.case7(num=1)

                        if self.place[7] == 2:
                            if 2 != self.place[4] == self.place[1] == 1 and self.place[7] == 2:
                                self.case8(num=1)
                            elif 2 != self.place[6] == self.place[8] == 1 and self.place[7] == 2:
                                self.case8(num=1)

                        if self.place[8] == 2 and self.goo == True:
                            if 2 != self.place[5] == self.place[2] == 1 and self.place[8] == 2:
                                self.case9(num=1)
                            elif 2 != self.place[6] == self.place[7] == 1 and self.place[8] == 2:
                                self.case9(num=1)
                            elif 2 != self.place[0] == self.place[4] == 1 and self.place[8] == 2:
                                self.case9(num=1)
                    # ----------
                    if self.place[0] == 2 and self.goo == True:
                        if 2 != self.place[4] == self.place[8] != 1 and self.place[0] == 2:
                            self.case1(num=1)
                        elif 2 != self.place[1] == self.place[2] != 1 and self.place[0] == 2:
                            self.case1(num=1)
                        elif 2 != self.place[3] == self.place[6] != 1 and self.place[0] == 2:
                            self.case1(num=1)

                    if self.place[1] == 2 and self.goo == True:
                        if 2 != self.place[0] == self.place[2] != 1 and self.place[1] == 2:
                            self.case2(num=1)
                        elif 2 != self.place[4] == self.place[7] != 1 and self.place[1] == 2:
                            self.case2(num=1)

                    if self.place[2] == 2 and self.goo == True:
                        if 2 != self.place[0] == self.place[1] != 1 and self.place[2] == 2:
                            self.case3(num=1)
                        elif 2 != self.place[4] == self.place[6] != 1 and self.place[2] == 2:
                            self.case3(num=1)
                        elif 2 != self.place[5] == self.place[8] != 1 and self.place[2] == 2:
                            self.case3(num=1)

                    if self.place[3] == 2 and self.goo == True:
                        if 2 != self.place[4] == self.place[5] != 1 and self.place[3] == 2:
                            self.case4(num=1)
                        if 2 != self.place[0] == self.place[6] != 1 and self.place[5] == 2:
                            self.case4(num=1)

                    if self.place[4] == 2 and self.goo == True:
                        if 2 != self.place[3] == self.place[5] != 1 and self.place[4] == 2:
                            self.case5(num=1)
                        elif 2 != self.place[0] == self.place[8] != 1 and self.place[4] == 2:
                            self.case5(num=1)
                        elif 2 != self.place[1] == self.place[7] != 1 and self.place[4] == 2:
                            self.case5(num=1)
                        elif 2 != self.place[2] == self.place[6] != 1 and self.place[4] == 2:
                            self.case5(num=1)

                    if self.place[5] == 2 and self.goo == True:
                        if 2 != self.place[3] == self.place[4] != 1 and self.place[5] == 2:
                            self.case6(num=1)
                        elif 2 != self.place[2] == self.place[8] != 1 and self.place[5] == 2:
                            self.case6(num=1)

                    if self.place[6] == 2 and self.goo == True:
                        if 2 != self.place[4] == self.place[2] != 1 and self.place[6] == 2:
                            self.case7(num=1)
                        elif 2 != self.place[0] == self.place[3] != 1 and self.place[6] == 2:
                            self.case7(num=1)
                        elif 2 != self.place[7] == self.place[8] != 1 and self.place[6] == 2:
                            self.case7(num=1)

                    if self.place[7] == 2 and self.goo == True:
                        if 2 != self.place[4] == self.place[1] != 1 and self.place[7] == 2:
                            self.case8(num=1)
                        elif 2 != self.place[6] == self.place[8] != 1 and self.place[7] == 2:
                            self.case8(num=1)

                    if self.place[8] == 2 and self.goo == True:
                        if 2 != self.place[5] == self.place[2] != 1 and self.place[8] == 2:
                            self.case9(num=1)
                        elif 2 != self.place[6] == self.place[7] != 1 and self.place[8] == 2:
                            self.case9(num=1)
                        elif 2 != self.place[0] == self.place[4] != 1 and self.place[8] == 2:
                            self.case9(num=1)

                    if self.goo == True and len(lista) > 1:
                        lista = []
                        print(self.place)
                        for pos, c in enumerate(self.place):
                            if c == 2:
                                lista.append(pos)
                        cg = choice(lista)
                        print(cg)
                        if cg == 0:
                            self.case1(num=1)
                        elif cg == 1:
                            self.case2(num=1)
                        elif cg == 2:
                            self.case3(num=1)
                        elif cg == 3:
                            self.case4(num=1)
                        elif cg == 4:
                            self.case5(num=1)
                        elif cg == 5:
                            self.case6(num=1)
                        elif cg == 6:
                            self.case7(num=1)
                        elif cg == 7:
                            self.case8(num=1)
                        elif cg == 8:
                            self.case9(num=1)
                        else:
                            pass


                elif self.gamer == 1 and len(lista) > 1:
                    if self.goo == True and len(lista) > 1:
                        if self.place[0] == 2 and self.goo == True:
                            if 2 != self.place[4] == self.place[8] == 0 and self.place[0] == 2:
                                self.case1(num=0)
                            elif 2 != self.place[1] == self.place[2] == 0 and self.place[0] == 2:
                                self.case1(num=0)
                            elif 2 != self.place[3] == self.place[6] == 0 and self.place[0] == 2:
                                self.case1(num=0)

                        if self.place[1] == 2 and self.goo == True:
                            if 2 != self.place[0] == self.place[2] == 0 and self.place[1] == 2:
                                self.case2(num=0)
                            elif 2 != self.place[4] == self.place[7] == 0 and self.place[1] == 2:
                                self.case2(num=0)

                        if self.place[2] == 2 and self.goo == True:
                            if 2 != self.place[0] == self.place[1] == 0 and self.place[2] == 2:
                                self.case3(num=0)
                            elif 2 != self.place[4] == self.place[6] == 0 and self.place[2] == 2:
                                self.case3(num=0)
                            elif 2 != self.place[5] == self.place[8] == 0 and self.place[2] == 2:
                                self.case3(num=0)

                        if self.place[3] == 2 and self.goo == True:
                            if 2 != self.place[4] == self.place[5] == 0 and self.place[3] == 2:
                                self.case4(num=0)
                            elif 2 != self.place[0] == self.place[6] == 0 and self.place[5] == 2:
                                self.case4(num=0)

                        if self.place[4] == 2 and self.goo == True:
                            if 2 != self.place[3] == self.place[5] == 0 and self.place[4] == 2:
                                self.case5(num=0)
                            elif 2 != self.place[0] == self.place[8] == 0 and self.place[4] == 2:
                                self.case5(num=0)
                            elif 2 != self.place[1] == self.place[7] == 0 and self.place[4] == 2:
                                self.case5(num=0)
                            elif 2 != self.place[2] == self.place[6] == 0 and self.place[4] == 2:
                                self.case5(num=0)

                        if self.place[5] == 2 and self.goo == True:
                            if 2 != self.place[3] == self.place[4] == 0 and self.place[5] == 2:
                                self.case6(num=0)
                            elif 2 != self.place[2] == self.place[8] == 0 and self.place[5] == 2:
                                self.case6(num=0)

                        if self.place[6] == 2 and self.goo == True:
                            if 2 != self.place[4] == self.place[2] == 0 and self.place[6] == 2:
                                self.case7(num=0)
                            elif 2 != self.place[0] == self.place[3] == 0 and self.place[6] == 2:
                                self.case7(num=0)
                            elif 2 != self.place[7] == self.place[8] == 0 and self.place[6] == 2:
                                self.case7(num=0)

                        if self.place[7] == 2 and self.goo == True:
                            if 2 != self.place[4] == self.place[1] == 0 and self.place[7] == 2:
                                self.case8(num=0)
                            elif 2 != self.place[6] == self.place[8] == 0 and self.place[7] == 2:
                                self.case8(num=0)

                        if self.place[8] == 2 and self.goo == True:
                            if 2 != self.place[5] == self.place[2] == 0 and self.place[8] == 2:
                                self.case9(num=0)
                            elif 2 != self.place[6] == self.place[7] == 0 and self.place[8] == 2:
                                self.case9(num=0)
                            elif 2 != self.place[0] == self.place[4] == 0 and self.place[8] == 2:
                                self.case9(num=0)
                    # --------------
                    if self.place[0] == 2 and self.goo == True:
                        if 2 != self.place[4] == self.place[8] != 0 and self.place[0] == 2:
                            self.case1(num=0)
                        elif 2 != self.place[1] == self.place[2] != 0 and self.place[0] == 2:
                            self.case1(num=0)
                        elif 2 != self.place[3] == self.place[6] != 0 and self.place[0] == 2:
                            self.case1(num=0)
                    else:
                        pass
                    if self.place[1] == 2 and self.goo == True:
                        if 2 != self.place[0] == self.place[2] != 0 and self.place[1] == 2:
                            self.case2(num=0)
                        elif 2 != self.place[4] == self.place[7] != 0 and self.place[1] == 2:
                            self.case2(num=0)
                    else:
                        pass

                    if self.place[2] == 2 and self.goo == True:
                        if 2 != self.place[0] == self.place[1] != 0 and self.place[2] == 2:
                            self.case3(num=0)
                        elif 2 != self.place[4] == self.place[6] != 0 and self.place[2] == 2:
                            self.case3(num=0)
                        elif 2 != self.place[5] == self.place[8] != 0 and self.place[2] == 2:
                            self.case3(num=0)

                    if self.place[3] == 2 and self.goo == True:
                        if 2 != self.place[4] == self.place[5] != 0 and self.place[3] == 2:
                            self.case4(num=0)
                        elif 2 != self.place[0] == self.place[6] != 0 and self.place[5] == 2:
                            self.case4(num=0)

                    if self.place[4] == 2 and self.goo == True:
                        if 2 != self.place[3] == self.place[5] != 0 and self.place[4] == 2:
                            self.case5(num=0)
                        elif 2 != self.place[0] == self.place[8] != 0 and self.place[4] == 2:
                            self.case5(num=0)
                        elif 2 != self.place[1] == self.place[7] != 0 and self.place[4] == 2:
                            self.case5(num=0)
                        elif 2 != self.place[2] == self.place[6] != 0 and self.place[4] == 2:
                            self.case5(num=0)

                    if self.place[5] == 2 and self.goo == True:
                        if 2 != self.place[3] == self.place[4] != 0 and self.place[5] == 2:
                            self.case6(num=0)
                        elif 2 != self.place[2] == self.place[8] != 0 and self.place[5] == 2:
                            self.case6(num=0)

                    if self.place[6] == 2 and self.goo == True:
                        if 2 != self.place[4] == self.place[2] != 0 and self.place[6] == 2:
                            self.case7(num=0)
                        elif 2 != self.place[0] == self.place[3] != 0 and self.place[6] == 2:
                            self.case7(num=0)
                        elif 2 != self.place[7] == self.place[8] != 0 and self.place[6] == 2:
                            self.case7(num=0)

                    if self.place[7] == 2 and self.goo == True:
                        if 2 != self.place[4] == self.place[1] != 0 and self.place[7] == 2:
                            self.case8(num=0)
                        elif 2 != self.place[6] == self.place[8] != 0 and self.place[7] == 2:
                            self.case8(num=0)

                    if self.place[8] == 2 and self.goo == True:
                        if 2 != self.place[5] == self.place[2] != 0 and self.place[8] == 2:
                            self.case9(num=0)
                        elif 2 != self.place[6] == self.place[7] != 0 and self.place[8] == 2:
                            self.case9(num=0)
                        elif 2 != self.place[0] == self.place[4] != 0 and self.place[8] == 2:
                            self.case9(num=0)

                    if self.goo == True and len(lista) > 1:
                        lista = []
                        for pos, c in enumerate(self.place):
                            if c == 2:
                                lista.append(pos)
                        cg = choice(lista)
                        print(cg)
                        if cg == 0:
                            self.case1(num=0)
                        elif cg == 1:
                            self.case2(num=0)
                        elif cg == 2:
                            self.case3(num=0)
                        elif cg == 3:
                            self.case4(num=0)
                        elif cg == 4:
                            self.case5(num=0)
                        elif cg == 5:
                            self.case6(num=0)
                        elif cg == 6:
                            self.case7(num=0)
                        elif cg == 7:
                            self.case8(num=0)
                        elif cg == 8:
                            self.case9(num=0)
                        else:
                            pass

            # This function is to check whether the computer won or not won the game.   
            self.verification()

        else:
            pass

    # The cases represent all buttons in the game and helps the computer to position the X or the O
    # when the user plays against the computer.
    def case1(self, num: int = 2):
        self.place[0] = num
        self.pushButton_1.setStyleSheet(self.estado[num])
        self.pushButton_1.setDisabled(True)
        self.number = num
        self.goo = False

    def case2(self, num: int = 2):
        self.place[1] = num
        self.pushButton_2.setStyleSheet(self.estado[num])
        self.pushButton_2.setDisabled(True)
        self.number = num
        self.goo = False

    def case3(self, num: int = 2):
        self.place[2] = num
        self.pushButton_3.setStyleSheet(self.estado[num])
        self.pushButton_3.setDisabled(True)
        self.number = num
        self.goo = False

    def case4(self, num: int = 2):
        self.place[3] = num
        self.pushButton_4.setStyleSheet(self.estado[num])
        self.pushButton_4.setDisabled(True)
        self.number = num
        self.goo = False

    def case5(self, num: int = 2):
        self.place[4] = num
        self.pushButton_5.setStyleSheet(self.estado[num])
        self.pushButton_5.setDisabled(True)
        self.number = num
        self.goo = False

    def case6(self, num: int = 2):
        self.place[5] = num
        self.pushButton_6.setStyleSheet(self.estado[num])
        self.pushButton_6.setDisabled(True)
        self.number = num
        self.goo = False

    def case7(self, num: int = 2):
        self.place[6] = num
        self.pushButton_7.setStyleSheet(self.estado[num])
        self.pushButton_7.setDisabled(True)
        self.number = num
        self.goo = False

    def case8(self, num: int = 2):
        self.place[7] = num
        self.pushButton_8.setStyleSheet(self.estado[num])
        self.pushButton_8.setDisabled(True)
        self.number = num
        self.goo = False

    def case9(self, num: int = 2):
        self.place[8] = num
        self.pushButton_9.setStyleSheet(self.estado[num])
        self.pushButton_9.setDisabled(True)
        self.number = num
        self.goo = False

    # This function is to verify who won, X or O.
    def verification(self):
        if self.place[0] == self.place[1] and self.place[1] == self.place[2] != 2:
            self.message(num=self.place[0])
            self.game_over()

        elif self.place[3] == self.place[4] and self.place[4] == self.place[5] != 2:
            self.message(num=self.place[3])
            self.game_over()

        elif self.place[6] == self.place[7] and self.place[7] == self.place[8] != 2:
            self.message(num=self.place[6])
            self.game_over()

        elif self.place[0] == self.place[4] and self.place[4] == self.place[8] != 2:
            self.message(num=self.place[0])
            self.game_over()

        elif self.place[2] == self.place[4] and self.place[4] == self.place[6] != 2:
            self.message(num=self.place[2])
            self.game_over()

        elif self.place[0] == self.place[3] and self.place[3] == self.place[6] != 2:
            self.message(num=self.place[0])
            self.game_over()

        elif self.place[1] == self.place[4] and self.place[4] == self.place[7] != 2:
            self.message(num=self.place[1])
            self.game_over()

        elif self.place[2] == self.place[5] and self.place[5] == self.place[8] != 2:
            self.message(num=self.place[2])
            self.game_over()

    # This function serves to mark the end of the game by disabling the game buttons.
    def game_over(self):
        self.game_finish = True
        self.pushButton_1.setDisabled(True)
        self.pushButton_2.setDisabled(True)
        self.pushButton_3.setDisabled(True)
        self.pushButton_4.setDisabled(True)
        self.pushButton_5.setDisabled(True)
        self.pushButton_6.setDisabled(True)
        self.pushButton_7.setDisabled(True)
        self.pushButton_8.setDisabled(True)
        self.pushButton_9.setDisabled(True)
        self.sound = QtMultimedia.QSound("gameover.wav")
        self.sound.play()

    # This function serve to show a message from win to X or O.
    def message(self, num: int = 2):
        if num == 1:
            self.label.setText(
                "<html><head/><body><p><span style=\" font-size:28pt; font-style:italic; color:#fa00a8;\">O</span><span style=\" font-size:28pt; font-style:italic;\"> wins the match!</span></p></body></html>")
        else:
            self.label.setText(
                "<html><head/><body><p><span style=\" font-size:28pt; font-style:italic; color:#fa00a8;\">X</span><span style=\" font-size:28pt; font-style:italic;\"> wins the match!</span></p></body></html>")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Jogo da velha"))
        self.vs_button.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Joge contra o computador</p></body></html>"))
        self.vs_button.setText(_translate("MainWindow", "VS"))


import rec

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
